const mockSupabase = {
  from: jest.fn().mockReturnThis(),
  select: jest.fn().mockReturnThis(),
  insert: jest.fn().mockReturnThis(),
  update: jest.fn().mockReturnThis(),
  delete: jest.fn().mockReturnThis(),
  eq: jest.fn().mockReturnThis(),
  in: jest.fn().mockReturnThis(),
  order: jest.fn().mockReturnThis(),
  limit: jest.fn().mockReturnThis(),
  single: jest.fn().mockResolvedValue({ data: null, error: null }),
  not: jest.fn().mockReturnThis(),
  auth: {
    getUser: jest.fn().mockResolvedValue({ data: { user: null }, error: null }),
    signOut: jest.fn().mockResolvedValue({}),
    signInWithOAuth: jest.fn().mockResolvedValue({}),
    onAuthStateChange: jest.fn().mockReturnValue({ data: { subscription: { unsubscribe: jest.fn() } } }),
  },
  rpc: jest.fn().mockResolvedValue({ data: 'member', error: null }),
};

module.exports = {
  supabase: mockSupabase,
  isSupabaseConfigured: true,
  getCurrentUser: jest.fn().mockResolvedValue({ id: 'test-user-id', email: 'test@test.com' }),
  getMyRole: jest.fn().mockResolvedValue('member'),
  getProfile: jest.fn().mockResolvedValue({ id: 'test-user-id', full_name: 'Test User', email: 'test@test.com' }),
  signInWithGoogle: jest.fn().mockResolvedValue({}),
  signOut: jest.fn().mockResolvedValue({}),
  onAuthStateChange: jest.fn(),
  createGroup: jest.fn().mockResolvedValue({ id: 'group-1', name: 'Test Group' }),
  getMyGroups: jest.fn().mockResolvedValue([]),
  sendInvitation: jest.fn().mockResolvedValue({}),
  getGroupInvitations: jest.fn().mockResolvedValue([]),
  acceptInvitation: jest.fn().mockResolvedValue({ success: true }),
  getMyContributions: jest.fn().mockResolvedValue([]),
  getAllContributions: jest.fn().mockResolvedValue([]),
  updateContributionStatus: jest.fn().mockResolvedValue({}),
  recordContribution: jest.fn().mockResolvedValue({}),
  getPayoutSchedule: jest.fn().mockResolvedValue([]),
  savePayoutSchedule: jest.fn().mockResolvedValue([]),
  markPayoutPaid: jest.fn().mockResolvedValue({}),
  getMyMeetings: jest.fn().mockResolvedValue([]),
  getGroupMeetings: jest.fn().mockResolvedValue([]),
  createMeeting: jest.fn().mockResolvedValue({}),
  updateMeetingMinutes: jest.fn().mockResolvedValue({}),
  deleteMeeting: jest.fn().mockResolvedValue({}),
  getLatestInterestRates: jest.fn().mockResolvedValue({ repo_rate: 6.75, prime_rate: 10.25, source: 'SARB', fetched_at: new Date().toISOString() }),
  getContributionCompliance: jest.fn().mockResolvedValue([]),
  getContributionsByMonth: jest.fn().mockResolvedValue([]),
};
